//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parcial3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleMsg
    {
        public long DetId { get; set; }
        public Nullable<long> Mensaje { get; set; }
        public string MensajeDescripcion { get; set; }
        public int CostoId { get; set; }
    
        public virtual Costo Costo { get; set; }
        public virtual Mensaje Mensaje1 { get; set; }
    }
}
