//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parcial3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TelefonoE
    {
        public long EstId { get; set; }
        public long Telefono { get; set; }
        public System.DateTime TiempoConectado { get; set; }
        public System.DateTime TiempoDesconectado { get; set; }
        public long TotalMensajesEnviados { get; set; }
        public long TotalMensajesRecibidos { get; set; }
    
        public virtual Telefono Telefono1 { get; set; }
    }
}
